package cn.cordys.crm.system.constants;

public enum UserViewResourceType {
    OPPORTUNITY,
    OPPORTUNITY_QUOTATION,
    CUSTOMER,
    CUSTOMER_CONTACT,
    CLUE,
    CUSTOMER_POOL,
    CLUE_POOL,
    FOLLOW_PLAN,
    FOLLOW_RECORD,
    CONTRACT,
    CONTRACT_INVOICE,
    CONTRACT_PAYMENT_PLAN,
	CONTRACT_PAYMENT_RECORD
}