export const AgentChatStreamUrl = '/agent/chat/stream'; // Agent 对话流式响应
export const AgentChatCancelUrl = '/agent/chat/cancel'; // Agent 取消流式响应
export const AgentChatUrl = '/agent/chat'; // Agent 对话
export const AgentChatConfirmUrl = '/agent/confirm'; // Agent 确认判断问题
export const AgentConversationPageUrl = '/agent-conversation/page'; // 分页获取历史对话列表
export const AgentConversationDetailUrl = '/agent-conversation/get'; // 获取对话消息详情
export const AgentConversationDeleteUrl = '/agent-conversation/delete'; // 删除对话及其全部消息
export const AgentConversationRenameUrl = '/agent-conversation/rename'; // 重命名历史对话: /{conversationId}
export const AgentChatFileUploadUrl = '/agent/chat/file/upload'; // 上传对话文件
export const AgentMcpConfigListUrl = '/agent-mcp-config/list'; // 查询当前用户 MCP 配置列表
export const AgentMcpConfigImportUrl = '/agent-mcp-config/import'; // 导入 MCP 配置文件
export const AgentMcpConfigDeleteUrl = '/agent-mcp-config/delete'; // 删除 MCP 配置
export const SmartDataOverviewUrl = '/smart/data-overview'; // 智慧工作台数据概览
export const SmartDataOverviewRegenerateUrl = '/smart/data-overview/regenerate'; // 数据概览-重新生成
export const SmartAiSummaryUrl = '/smart/ai-summary'; // AI 内容解读-查询
export const SmartAiSummaryRegenerateUrl = '/smart/ai-summary/regenerate'; // AI 内容解读-重新生成
export const AgentActionSuggestionPageUrl = '/agent-action-suggestion/page'; // AI 跟进建议分页查询
export const AgentActionSuggestionIgnoreUrl = '/agent-action-suggestion/ignore'; // 忽略建议
export const AgentActionSuggestionSubmitUrl = '/agent-action-suggestion/submit'; // 提交执行建议
export const AgentActionApprovePageUrl = '/agent-action-approve/page'; // AI 方案审核分页查询
export const AgentActionApproveIgnoreUrl = '/agent-action-approve/ignore'; // 忽略或拒绝审核
export const AgentActionApproveConfirmUrl = '/agent-action-approve/confirm'; // 确认审核并异步提交执行
